[project]
name = "kindle-vocab"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiofiles>=24.1.0",
    "fastapi>=0.115.6",
    "jinja2>=3.1.5",
    "ruff>=0.11.8",
    "uvicorn>=0.34.0",
]
